### PR TITLE
Fix up issue #2 Previous Hash is not updated when mining

### PR DESCRIPTION
**Pull request by ejc123**

### CODE REVIEW

**Comment by alexdovzhanyn** [comment]
Hey! Thanks for taking the time to create an issue & pr for this :) I think there might be a bit of confusion as to how this is intended to work. Within the blockchain, each block has a `previous_hash` property that refers to the hash of the previous block (this is what links the blocks together into a chain). After running the miner for a few second and generating a chain, i found that each block had the previous_hash attached properly. If you look at the results here:

```elixir
iex(1)> UltraDark.Ledger.retrieve_chain
[%UltraDark.Blockchain.Block{difficulty: 6.0,
  hash: "0000000C1817A2457968FB60BC9E2A5F61660D25E77CD4CA8D1B36D62CBFEDFF",
  index: 3, nonce: 22628641,
  previous_hash: "0000004F4A51758FAA0FCB59B6D69B254DB02A1108D6C8E452463E012A70FDC0",
  timestamp: "2018-01-31 01:04:14.134760Z", transactions: []},
 %UltraDark.Blockchain.Block{difficulty: 6.0,
  hash: "0000004F4A51758FAA0FCB59B6D69B254DB02A1108D6C8E452463E012A70FDC0",
  index: 2, nonce: 4312278,
  previous_hash: "000000FA60F7B0636FBBABC27929C7D46B011E44FC5E6F68BBA93E48914079F1",
  timestamp: "2018-01-31 01:02:46.067569Z", transactions: []},
 %UltraDark.Blockchain.Block{difficulty: 6.0,
  hash: "00000087B093F4BBA0FE7784DCA8FA93552A25B18C49573E0D08081CD93E6695",
  index: 4, nonce: 436919,
  previous_hash: "0000000C1817A2457968FB60BC9E2A5F61660D25E77CD4CA8D1B36D62CBFEDFF",
  timestamp: "2018-01-31 01:45:07.547983Z", transactions: []},
 %UltraDark.Blockchain.Block{difficulty: 6.0,
  hash: "000000FA60F7B0636FBBABC27929C7D46B011E44FC5E6F68BBA93E48914079F1",
  index: 1, nonce: 3479536,
  previous_hash: "79644A8F062F1BA9F7A32AF2242C04711A634D42F0628ADA6B985B3D21296EEA",
  timestamp: "2018-01-31 01:01:41.035620Z", transactions: []}]
```

You'll notice 2 things:
1. The blocks are out of order in the chain (this is a bug i just noticed. It should be highest index first), and the genesis block (index 0) is not being saved to leveldb (another bug)
2. If you follow the chain based on the index, you'll see that each blocks `previous_hash` is equal to the `hash` of the block with the index before it

Looks like this is working properly, although there are some bugs with the retrieve_chain function

**Comment by ejc123** [comment]
Ok.  Now I understand how this works.  I was running Block.mine on it's own and couldn't see where previous_hash was set.  Now I see where Block.initialize is called with the most recent block added to the chain and previous_hash is set.
I'll withdraw this PR and close the bug.

**Comment by ejc123** [comment]
Bug was invalid due to my misunderstanding of the code flow.

**Comment by alexdovzhanyn** [comment]
Thanks!

**Pull request closed without merging**
